# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Qtui/Qtui_frame_pack.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FramePack(object):
    def setupUi(self, FramePack):
        FramePack.setObjectName("FramePack")
        FramePack.resize(768, 556)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(FramePack)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_recive = QtWidgets.QWidget(FramePack)
        self.widget_recive.setMinimumSize(QtCore.QSize(150, 250))
        self.widget_recive.setMaximumSize(QtCore.QSize(200, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_recive.setFont(font)
        self.widget_recive.setObjectName("widget_recive")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_recive)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_draw_x = QtWidgets.QPushButton(self.widget_recive)
        self.pushButton_draw_x.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_draw_x.setFont(font)
        self.pushButton_draw_x.setObjectName("pushButton_draw_x")
        self.gridLayout.addWidget(self.pushButton_draw_x, 0, 2, 1, 1)
        self.pushButton_draw_xy = QtWidgets.QPushButton(self.widget_recive)
        self.pushButton_draw_xy.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_draw_xy.setFont(font)
        self.pushButton_draw_xy.setObjectName("pushButton_draw_xy")
        self.gridLayout.addWidget(self.pushButton_draw_xy, 1, 2, 1, 1)
        self.label_data_num = QtWidgets.QLabel(self.widget_recive)
        self.label_data_num.setMinimumSize(QtCore.QSize(53, 0))
        self.label_data_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_data_num.setFont(font)
        self.label_data_num.setObjectName("label_data_num")
        self.gridLayout.addWidget(self.label_data_num, 3, 1, 1, 3)
        self.label_y_value = QtWidgets.QLabel(self.widget_recive)
        self.label_y_value.setMinimumSize(QtCore.QSize(20, 0))
        self.label_y_value.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_y_value.setFont(font)
        self.label_y_value.setText("")
        self.label_y_value.setObjectName("label_y_value")
        self.gridLayout.addWidget(self.label_y_value, 1, 1, 1, 1)
        self.pushButton_data_clear = QtWidgets.QPushButton(self.widget_recive)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_data_clear.setFont(font)
        self.pushButton_data_clear.setObjectName("pushButton_data_clear")
        self.gridLayout.addWidget(self.pushButton_data_clear, 2, 0, 1, 1)
        self.label_y = QtWidgets.QLabel(self.widget_recive)
        self.label_y.setMinimumSize(QtCore.QSize(0, 0))
        self.label_y.setMaximumSize(QtCore.QSize(26, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_y.setFont(font)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 1, 0, 1, 1)
        self.label_x = QtWidgets.QLabel(self.widget_recive)
        self.label_x.setMinimumSize(QtCore.QSize(0, 0))
        self.label_x.setMaximumSize(QtCore.QSize(26, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_x.setFont(font)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 0, 0, 1, 1)
        self.label_x_value = QtWidgets.QLabel(self.widget_recive)
        self.label_x_value.setMinimumSize(QtCore.QSize(20, 0))
        self.label_x_value.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_x_value.setFont(font)
        self.label_x_value.setText("")
        self.label_x_value.setObjectName("label_x_value")
        self.gridLayout.addWidget(self.label_x_value, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_recive)
        self.label_10.setMinimumSize(QtCore.QSize(53, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.pushButton_data_save = QtWidgets.QPushButton(self.widget_recive)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_data_save.setFont(font)
        self.pushButton_data_save.setObjectName("pushButton_data_save")
        self.gridLayout.addWidget(self.pushButton_data_save, 2, 1, 1, 3)
        self.label_x.raise_()
        self.label_10.raise_()
        self.pushButton_data_save.raise_()
        self.label_data_num.raise_()
        self.label_y.raise_()
        self.pushButton_data_clear.raise_()
        self.label_y_value.raise_()
        self.label_x_value.raise_()
        self.pushButton_draw_xy.raise_()
        self.pushButton_draw_x.raise_()
        self.verticalLayout_3.addWidget(self.widget_recive)
        self.pushButton_pack_set = QtWidgets.QPushButton(FramePack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_pack_set.setFont(font)
        self.pushButton_pack_set.setObjectName("pushButton_pack_set")
        self.verticalLayout_3.addWidget(self.pushButton_pack_set)
        self.widget_com = QtWidgets.QWidget(FramePack)
        self.widget_com.setObjectName("widget_com")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_com)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_com)
        self.widget_send = QtWidgets.QWidget(FramePack)
        self.widget_send.setMaximumSize(QtCore.QSize(200, 300))
        self.widget_send.setObjectName("widget_send")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_send)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.widget_send)
        self.label_8.setMinimumSize(QtCore.QSize(47, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_send)
        self.label_9.setMinimumSize(QtCore.QSize(47, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.pushButton_send = QtWidgets.QPushButton(self.widget_send)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout.addWidget(self.pushButton_send)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.widget_send)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(FramePack)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setBaseSize(QtCore.QSize(5, 4))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget.setRowCount(21)
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tableWidget_2 = QtWidgets.QTableWidget(FramePack)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableWidget_2.setBaseSize(QtCore.QSize(5, 4))
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_2.setRowCount(10)
        self.tableWidget_2.setColumnCount(16)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(FramePack)
        QtCore.QMetaObject.connectSlotsByName(FramePack)

    def retranslateUi(self, FramePack):
        _translate = QtCore.QCoreApplication.translate
        FramePack.setWindowTitle(_translate("FramePack", "Frame"))
        self.pushButton_draw_x.setText(_translate("FramePack", "画图x"))
        self.pushButton_draw_xy.setText(_translate("FramePack", "画图xy"))
        self.label_data_num.setText(_translate("FramePack", "100/500"))
        self.pushButton_data_clear.setText(_translate("FramePack", "清空"))
        self.label_y.setText(_translate("FramePack", "y:"))
        self.label_x.setText(_translate("FramePack", "x:"))
        self.label_10.setText(_translate("FramePack", "缓存大小"))
        self.pushButton_data_save.setText(_translate("FramePack", "保存数据"))
        self.pushButton_pack_set.setText(_translate("FramePack", "包信息查后与设置"))
        self.label_8.setText(_translate("FramePack", "选中"))
        self.label_9.setText(_translate("FramePack", "1"))
        self.pushButton_send.setText(_translate("FramePack", "发送"))
